ddash/apps/base/urls.py
from django.views.generic.base import TemplateView
from django.urls import path

from . import views

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
]

app_name = "base"

ddash/apps/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("testrun/detail/<int:id>", views.testrun_detail, name="testrun_detail"),
]

app_name = "main"

ddash/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import TemplateView

from ddash.apps.base import urls as base_urls
from ddash.apps.main import urls as main_urls
from ddash.apps.users import urls as user_urls
from ddash.apps.api import urls as api_urls

admin.site.site_header = "Dyninst Dashboard Admin"
admin.site.site_title = "Dyninst Dashboard Admin"
admin.site.index_title = "Dyninst Dashboard Admin"

# Configure custom error pages
handler404 = "ddash.apps.base.views.handler404"
handler500 = "ddash.apps.base.views.handler500"

admin.autodiscover()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(base_urls, namespace="base")),
    path("api/", include(api_urls, namespace="api")),
    path("", include(main_urls, namespace="main")),
    path("", include(user_urls, namespace="users")),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
]

ddash/apps/api/views/base.py
from django.conf import settings

from ratelimit.mixins import RatelimitMixin

from ddash.settings import cfg
from ddash.version import __version__
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView


class ServiceInfo(RatelimitMixin, APIView):
    """Return a 200 response to indicate a running service, along with
    metadata about the service. This is similar to https://ga4gh.github.io/,
    but not for a workflow so only a subset of fields.
    """

    ratelimit_key = "ip"
    ratelimit_rate = settings.VIEW_RATE_LIMIT
    ratelimit_block = settings.VIEW_RATE_LIMIT_BLOCK
    ratelimit_method = "GET"
    renderer_classes = (JSONRenderer,)

    def get(self, request):
        print("GET /")

        data = {
            "id": "ddash",
            "status": "running",
            "name": "Dyninst Dashboard (ddash)",
            "description": "This service provides a dashboard for Dyninst results",
            "organization": {"name": "dyninst", "url": "https://github.com/dyninst"},
            "contactUrl": cfg.HELP_CONTACT_URL,
            "documentationUrl": "https://github.com/dyninst/dashboard",
            "createdAt": settings.SERVER_CREATION_DATE,
            "updatedAt": cfg.UPDATED_AT,
            "environment": cfg.ENVIRONMENT,
            "version": __version__,
            "auth_instructions_url": "OAauth2 is currently disabled.",
        }

        # Must make model json serializable
        return Response(status=200, data=data)

ddash/apps/base/views.py
from django.http import HttpResponse
from django.shortcuts import render


def handler404(request, exception):
    response = render(request, "base/404.html", {})
    response.status_code = 404
    return response


def handler500(request):
    response = render(request, "base/500.html", {})
    response.status_code = 500
    return response


def warmup():
    return HttpResponse(status=200)

ddash/apps/base/templates/base/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
    <head>

        <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
        <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
        <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
        <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Dyninst Dashboard{% endblock %}</title>
        <meta name="description" content="Dyninst Dashboard" />
        <meta name="keywords" content="dyninst,tests,dashboard" />
        <meta name="author" content="vsoch" />
        <meta name="robots" content="noindex,nofollow" />
        <link rel="icon" type="image/ico" href="/static/img/favicon.ico"/>

        <!-- Facebook and Twitter integration -->
        <meta property="og:title" content="Dyninst Dashboard"/>
        <meta property="og:image" content="{% static 'img/dyninst-dragon.png.png' %}"/>
        <meta property="og:url" content="{{ DOMAIN }}"/>
        <meta property="og:site_name" content="Dyninst Dashboard"/>

        <meta property="og:description" content="Dyninst Dashboard"/>
        <meta name="twitter:title" content="Dyninst Dashboard" />
        <meta name="twitter:image" content="{% static 'img/dyninst-dragon.png' %}" />
        {% if TWITTER_USERNAME %}<meta name="twitter:url" content="https://twitter.com/{{ TWITTER_USERNAME }}" />{% endif %}
        <meta name="twitter:card" content="summary" />

        {% include "base/ga.html" %}

        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all">
        <link href="{% static 'css/jquery-ui-1.10.4.css' %}" rel="stylesheet" />
        <link href="{% static 'css/nv.d3.css' %}" rel="stylesheet" />
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
        <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
        <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'css/syntax.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" type="text/css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" type="text/css">
        
        {% block fonts %}{% endblock %}
        {% block css %}{% endblock %}
        {% block head %}{% endblock %}
    </head>

    {% block body %}
    <body bgcolor="white">
    {% include "base/loader.html" %}
    {% include "base/navigation.html" %}
    <div id="main_content" style="padding-top:30px">
    {% block container %}{% block content %}{% endblock %}{% endblock %}
    </div>
    <div id="line"></div>
    {% include "base/footer.html" %}

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/ScrollToPlugin.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-switch.js' %}"></script>
    <script src="{% static 'js/flexslider.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

    {% block scripts %}{% endblock %}
    </body>
    {% endblock %}

</html>

ddash/apps/base/templates/base/footer.html
{% load static %}
  <div id="footerlinks" class="clearfix" style="padding-top:100px">
    <span id="footertext" style="padding-right:30px">
      Dyninst Dashboard {{ DYNINST_DASHBOARD_VERSION }}
      with ❤️ from @vsoch |
      <a href="https://github.com/dyninst/dashboard/issues" target="blank">Ask for help</a>
      </span><!-- end ngIf: ::cdash.generationtime -->
    </span>
  </div>

ddash/apps/base/templates/base/ga.html
{% if GOOGLE_ANALYTICS_SITE and GOOGLE_ANALYTICS_ID %}
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '{{ GOOGLE_ANALYTICS_ID }}', '{{ GOOGLE_ANALYTICS_SITE }}');
    ga('send', 'pageview');
</script>
{% endif %}

ddash/apps/base/templates/base/loader.html
<style>
#fade {
   background-color: #333;
   opacity: 0.9;
   width: 100%;
   height: 100%;
   position: absolute;
   z-index: 2000;
   top: 0px;
}

#loading {
  display: inline-block;
  width: 50px;
  height: 50px;
  border: 3px solid rgba(255,255,255,.3);
  border-radius: 50%;
  top: 50%;
  left: 50%;
  position: absolute;
  border-top-color: #fff;
  animation: spin 1s ease-in-out infinite;
  -webkit-animation: spin 1s ease-in-out infinite;
  z-index: 1001;
}

.loader,
.loader:before,
.loader:after {
  border-radius: 50%;
  width: 2.5em;
  height: 2.5em;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
  -webkit-animation: load7 1.8s infinite ease-in-out;
  animation: load7 1.8s infinite ease-in-out;
}

.loader {
  color: #ffffff;
  font-size: 10px;
  margin: 80px auto;
  position: relative;
  text-indent: -9999em;
  -webkit-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
  -webkit-animation-delay: -0.16s;
  animation-delay: -0.16s;
}
.loader:before,
.loader:after {
  content: '';
  position: absolute;
  top: 0;
}
.loader:before {
  left: -3.5em;
  -webkit-animation-delay: -0.32s;
  animation-delay: -0.32s;
}
.loader:after {
  left: 3.5em;
}
@-webkit-keyframes load7 {
  0%,
  80%,
  100% {
    box-shadow: 0 2.5em 0 -1.3em;
  }
  40% {
    box-shadow: 0 2.5em 0 0;
  }
}
@keyframes load7 {
  0%,
  80%,
  100% {
    box-shadow: 0 2.5em 0 -1.3em;
  }
  40% {
    box-shadow: 0 2.5em 0 0;
  }
}

@keyframes spin {
  to { -webkit-transform: rotate(360deg); }
}
@-webkit-keyframes spin {
  to { -webkit-transform: rotate(360deg); }
}

@keyframes fade{
	0%{
		background: rgb(201, 145, 84);
	}
	
	50%{
		background: #90BBBF;
	}
	
	100%{
		background: rgb(201, 145, 84);
	}
}

@-webkit-keyframes pulse{
	0%{
		-webkit-transform: scale(1);
		transform: scale(1);
	}
	
	50%{
		-webkit-transform: scale(0.01);
		transform: scale(0.01);
	}
	
	100%{
		-webkit-transform: scale(1);
		transform: scale(1);
	}
}

@-webkit-keyframes fade{
	0%{
		background: rgb(201, 145, 84);
	}
	
	50%{
		background: #389CA6;
	}
	
	100%{
		background: rgb(201, 145, 84);
	}
}
</style>
<div id="fade" style="display:none">
  <div class="loader"></div>
</div>

ddash/apps/base/templates/base/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="{% url 'main:dashboard' %}">  
      <a href="{% url 'main:dashboard' %}">
        <img src="{% static 'img/dyninst-dragon.png' %}" height="40px" style="padding-left:10px"/>
      </a>      
      <span class="projectname" style="width:200px; padding-left:20px">Dyninst Dashboard</span>  
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:dashboard' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Analyses
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="">Something</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'api:internal_apis:docs' %}">API</a>
        </div>
      </li>-->
    </ul>
  </div>
</nav>

ddash/apps/base/templates/base/page.html
{% extends "base/base.html" %}
{% load static %}
{% block container %}
    <div class="wrapper">
        <div class="main-panel">
            {% include "base/navigation.html" %}
            {% include "messages/message.html" %}
            <div class="content">
                <div class="container-fluid">
                   {% block content %}{% endblock %}
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav>
                       <ul>
                           <li style="float:right;"><a target="_blank" href="{{ GITHUB_DOCUMENTATION }}"><i class="icon ti ti-book"></i></a></li>
                           <li style="float:right;"><a target="_blank" href="{{ GITHUB_REPOSITORY }}"><i class="icon ti ti-github"></i></a></li>
                           {% if TWITTER_USERNAME %}<li style="float:right;"><a target="_blank" href="https://twitter.com/{{ TWITTER_USERNAME }}"><i class="icon ti ti-twitter-alt"></i></a></li>{% endif %}
                       </ul>
                       <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="https://github.com/snakemake">Snakemake Community</a>, made with love for better workflows.
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>
{% endblock %}